# Generated by Django 5.0.4 on 2024-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_entrega3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
